/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PartsIndexRouteImport } from './routes/parts/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as BlueprintsIndexRouteImport } from './routes/blueprints/index'
import { Route as PartsNewRouteImport } from './routes/parts/new'
import { Route as PartsPartIdRouteImport } from './routes/parts/$partId'
import { Route as BlueprintsPickLocationRouteImport } from './routes/blueprints/pick-location'
import { Route as BlueprintsNewRouteImport } from './routes/blueprints/new'
import { Route as BlueprintsBlueprintIdRouteImport } from './routes/blueprints/$blueprintId'
import { Route as ApiVerifyTokenRouteImport } from './routes/api/verify-token'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsIndexRoute = PartsIndexRouteImport.update({
  id: '/parts/',
  path: '/parts/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsIndexRoute = BlueprintsIndexRouteImport.update({
  id: '/blueprints/',
  path: '/blueprints/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsNewRoute = PartsNewRouteImport.update({
  id: '/parts/new',
  path: '/parts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsPartIdRoute = PartsPartIdRouteImport.update({
  id: '/parts/$partId',
  path: '/parts/$partId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsPickLocationRoute = BlueprintsPickLocationRouteImport.update({
  id: '/blueprints/pick-location',
  path: '/blueprints/pick-location',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsNewRoute = BlueprintsNewRouteImport.update({
  id: '/blueprints/new',
  path: '/blueprints/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsBlueprintIdRoute = BlueprintsBlueprintIdRouteImport.update({
  id: '/blueprints/$blueprintId',
  path: '/blueprints/$blueprintId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyTokenRoute = ApiVerifyTokenRouteImport.update({
  id: '/api/verify-token',
  path: '/api/verify-token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/callback': typeof CallbackRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/api/verify-token': typeof ApiVerifyTokenRoute
  '/blueprints/$blueprintId': typeof BlueprintsBlueprintIdRoute
  '/blueprints/new': typeof BlueprintsNewRoute
  '/blueprints/pick-location': typeof BlueprintsPickLocationRoute
  '/parts/$partId': typeof PartsPartIdRoute
  '/parts/new': typeof PartsNewRoute
  '/blueprints/': typeof BlueprintsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/parts/': typeof PartsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/callback': typeof CallbackRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/api/verify-token': typeof ApiVerifyTokenRoute
  '/blueprints/$blueprintId': typeof BlueprintsBlueprintIdRoute
  '/blueprints/new': typeof BlueprintsNewRoute
  '/blueprints/pick-location': typeof BlueprintsPickLocationRoute
  '/parts/$partId': typeof PartsPartIdRoute
  '/parts/new': typeof PartsNewRoute
  '/blueprints': typeof BlueprintsIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/parts': typeof PartsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/callback': typeof CallbackRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/api/verify-token': typeof ApiVerifyTokenRoute
  '/blueprints/$blueprintId': typeof BlueprintsBlueprintIdRoute
  '/blueprints/new': typeof BlueprintsNewRoute
  '/blueprints/pick-location': typeof BlueprintsPickLocationRoute
  '/parts/$partId': typeof PartsPartIdRoute
  '/parts/new': typeof PartsNewRoute
  '/blueprints/': typeof BlueprintsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/parts/': typeof PartsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/callback'
    | '/home'
    | '/login'
    | '/logout'
    | '/api/verify-token'
    | '/blueprints/$blueprintId'
    | '/blueprints/new'
    | '/blueprints/pick-location'
    | '/parts/$partId'
    | '/parts/new'
    | '/blueprints/'
    | '/inventory/'
    | '/parts/'
    | '/settings/'
    | '/transactions/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/callback'
    | '/home'
    | '/login'
    | '/logout'
    | '/api/verify-token'
    | '/blueprints/$blueprintId'
    | '/blueprints/new'
    | '/blueprints/pick-location'
    | '/parts/$partId'
    | '/parts/new'
    | '/blueprints'
    | '/inventory'
    | '/parts'
    | '/settings'
    | '/transactions'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/callback'
    | '/home'
    | '/login'
    | '/logout'
    | '/api/verify-token'
    | '/blueprints/$blueprintId'
    | '/blueprints/new'
    | '/blueprints/pick-location'
    | '/parts/$partId'
    | '/parts/new'
    | '/blueprints/'
    | '/inventory/'
    | '/parts/'
    | '/settings/'
    | '/transactions/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  CallbackRoute: typeof CallbackRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ApiVerifyTokenRoute: typeof ApiVerifyTokenRoute
  BlueprintsBlueprintIdRoute: typeof BlueprintsBlueprintIdRoute
  BlueprintsNewRoute: typeof BlueprintsNewRoute
  BlueprintsPickLocationRoute: typeof BlueprintsPickLocationRoute
  PartsPartIdRoute: typeof PartsPartIdRoute
  PartsNewRoute: typeof PartsNewRoute
  BlueprintsIndexRoute: typeof BlueprintsIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  PartsIndexRoute: typeof PartsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/': {
      id: '/parts/'
      path: '/parts'
      fullPath: '/parts/'
      preLoaderRoute: typeof PartsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints/': {
      id: '/blueprints/'
      path: '/blueprints'
      fullPath: '/blueprints/'
      preLoaderRoute: typeof BlueprintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/new': {
      id: '/parts/new'
      path: '/parts/new'
      fullPath: '/parts/new'
      preLoaderRoute: typeof PartsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/$partId': {
      id: '/parts/$partId'
      path: '/parts/$partId'
      fullPath: '/parts/$partId'
      preLoaderRoute: typeof PartsPartIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints/pick-location': {
      id: '/blueprints/pick-location'
      path: '/blueprints/pick-location'
      fullPath: '/blueprints/pick-location'
      preLoaderRoute: typeof BlueprintsPickLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints/new': {
      id: '/blueprints/new'
      path: '/blueprints/new'
      fullPath: '/blueprints/new'
      preLoaderRoute: typeof BlueprintsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints/$blueprintId': {
      id: '/blueprints/$blueprintId'
      path: '/blueprints/$blueprintId'
      fullPath: '/blueprints/$blueprintId'
      preLoaderRoute: typeof BlueprintsBlueprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-token': {
      id: '/api/verify-token'
      path: '/api/verify-token'
      fullPath: '/api/verify-token'
      preLoaderRoute: typeof ApiVerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  CallbackRoute: CallbackRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ApiVerifyTokenRoute: ApiVerifyTokenRoute,
  BlueprintsBlueprintIdRoute: BlueprintsBlueprintIdRoute,
  BlueprintsNewRoute: BlueprintsNewRoute,
  BlueprintsPickLocationRoute: BlueprintsPickLocationRoute,
  PartsPartIdRoute: PartsPartIdRoute,
  PartsNewRoute: PartsNewRoute,
  BlueprintsIndexRoute: BlueprintsIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  PartsIndexRoute: PartsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
